# This file was generated by GoReleaser. DO NOT EDIT.
cask "spacedock" do
  version "0.20.4"

  on_macos do
    on_intel do
      sha256 "90c46e481de43063f7bc765f2f7fdd954ffb5bef1aa37a68374bf0962f17ce7e"
      url "https://github.com/spacedock-dev/spacedock/releases/download/v#{version}/spacedock_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "111492b697655ec1009215ba2576383b17e3c96c559fa20169696340ebc4d674"
      url "https://github.com/spacedock-dev/spacedock/releases/download/v#{version}/spacedock_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3d9025eca4b988f385af52f4568a6d26d7af238589656ccd99df741081386a12"
      url "https://github.com/spacedock-dev/spacedock/releases/download/v#{version}/spacedock_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "58436f92c9249902ff3a567e63aa2e284c676dadc9a0ac09791c0c3608dc5dc5"
      url "https://github.com/spacedock-dev/spacedock/releases/download/v#{version}/spacedock_#{version}_linux_arm64.tar.gz"
    end
  end

  name "spacedock"
  desc "Workflow launcher and first-officer dispatch for agentic dev"
  homepage "https://github.com/spacedock-dev/spacedock"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on cask: [
      "agentsview",
    ]

  binary "spacedock"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/spacedock"]
  end

  # No zap stanza required

  caveats <<~EOS
    Recommended companion (install separately):
      safehouse  — sandboxes agent runs (https://agent-safehouse.dev)
      brew install eugene1g/safehouse/agent-safehouse
  EOS
end
