# This file was generated by GoReleaser. DO NOT EDIT.
cask "spacedock@next" do
  version "0.27.0-pre0"

  on_macos do
    on_intel do
      sha256 "26074ffda2f13bc211480b94e0f790cdfaffcca88bcd2dde9df53e5959b17c0a"
      url "https://github.com/spacedock-dev/spacedock/releases/download/v#{version}/spacedock_#{version}_darwin_amd64_edge.tar.gz"
    end
    on_arm do
      sha256 "41575b59e00c5949edc32dc231772fe6e9208d8958a7f86f431dc8ca39dff9d7"
      url "https://github.com/spacedock-dev/spacedock/releases/download/v#{version}/spacedock_#{version}_darwin_arm64_edge.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ee3f51c725e114bb633ab3faddb3b0f1af72667ec6058d73c03bdfc4745e7ce1"
      url "https://github.com/spacedock-dev/spacedock/releases/download/v#{version}/spacedock_#{version}_linux_amd64_edge.tar.gz"
    end
    on_arm do
      sha256 "3efa56bd89abe5dfe9442858147a4b07ac7336932ce92ed8d6a390e1a7fc041d"
      url "https://github.com/spacedock-dev/spacedock/releases/download/v#{version}/spacedock_#{version}_linux_arm64_edge.tar.gz"
    end
  end

  name "spacedock@next"
  desc "Workflow launcher and first-officer dispatch for agentic dev (edge channel)"
  homepage "https://github.com/spacedock-dev/spacedock"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "spacedock",
    ]

  depends_on cask: [
      "agentsview",
    ]

  binary "spacedock"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/spacedock"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Recommended companion (install separately):
      safehouse  — sandboxes agent runs (https://agent-safehouse.dev)
      brew install eugene1g/safehouse/agent-safehouse
  EOS
end
