# This file was generated by GoReleaser. DO NOT EDIT.
cask "spacedock" do
  version "0.20.0"

  on_macos do
    on_intel do
      sha256 "a7dc26bde68c42d4240b7823305edc09f8d894d9be8b86dceb7087a0b6cf4721"
      url "https://github.com/spacedock-dev/spacedock/releases/download/v#{version}/spacedock_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "58ab29b97e0acbb3a9b31b2b1ed6901bf96b98f23adfd890dadb9aad9b45243d"
      url "https://github.com/spacedock-dev/spacedock/releases/download/v#{version}/spacedock_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b695cf48f2e91d8dcf2b43b44666c0fe74f93f10d1da4481515a44ba89283273"
      url "https://github.com/spacedock-dev/spacedock/releases/download/v#{version}/spacedock_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f83b5fd91e2efc6f1830c750fb8d8dc6e5160ece2526af1d12ef9bfc9544d5e2"
      url "https://github.com/spacedock-dev/spacedock/releases/download/v#{version}/spacedock_#{version}_linux_arm64.tar.gz"
    end
  end

  name "spacedock"
  desc "Workflow launcher and first-officer dispatch for agentic dev"
  homepage "https://github.com/spacedock-dev/spacedock"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spacedock"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/spacedock"]
  end

  # No zap stanza required

  caveats <<~EOS
    Recommended companions (not installed by brew):
      safehouse  — sandboxes agent runs (https://agent-safehouse.dev)
      agentsview — powers /spacedock:survey
  EOS
end
