# This file was generated by GoReleaser. DO NOT EDIT.
cask "spacedock" do
  version "0.26.0"

  on_macos do
    on_intel do
      sha256 "e3ac9cdc374bae82ad0d17d839fe5294da55ee9e3328e94ce8eb0f137929aef4"
      url "https://github.com/spacedock-dev/spacedock/releases/download/v#{version}/spacedock_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ff96b1772454a5919b6f7ccf9f9f6a01ba82f7de2c0a583c8a68240be698709b"
      url "https://github.com/spacedock-dev/spacedock/releases/download/v#{version}/spacedock_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8440b5e1ea00d606da8bdd2ed86cc704e5bb0f124ea53521131145a429c55248"
      url "https://github.com/spacedock-dev/spacedock/releases/download/v#{version}/spacedock_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3b6e1341f308f2f705e413a640f666b8144c350e4a7b172617f3522a2c4d9785"
      url "https://github.com/spacedock-dev/spacedock/releases/download/v#{version}/spacedock_#{version}_linux_arm64.tar.gz"
    end
  end

  name "spacedock"
  desc "Workflow launcher and first-officer dispatch for agentic dev"
  homepage "https://github.com/spacedock-dev/spacedock"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "spacedock@next",
    ]

  depends_on cask: [
      "agentsview",
    ]

  binary "spacedock"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/spacedock"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Recommended companion (install separately):
      safehouse  — sandboxes agent runs (https://agent-safehouse.dev)
      brew install eugene1g/safehouse/agent-safehouse
  EOS
end
