# This file was generated by GoReleaser. DO NOT EDIT.
cask "spacedock@next" do
  version "0.20.2"

  on_macos do
    on_intel do
      sha256 "bae6e91596cf950614d88f12b46fb825438a60e51894341576d29b44bd44d310"
      url "https://github.com/spacedock-dev/spacedock/releases/download/v#{version}/spacedock_#{version}_darwin_amd64_edge.tar.gz"
    end
    on_arm do
      sha256 "1688f9de840314e56f8b7e09297f256d548aeafed2f4abf5e61ba3317c470b2d"
      url "https://github.com/spacedock-dev/spacedock/releases/download/v#{version}/spacedock_#{version}_darwin_arm64_edge.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fcc99f184db88c722ccc2dc5a4a058e15c0e4db21ad6e6d3df5649c08eac7cc3"
      url "https://github.com/spacedock-dev/spacedock/releases/download/v#{version}/spacedock_#{version}_linux_amd64_edge.tar.gz"
    end
    on_arm do
      sha256 "9bae322986e222590baa5f3fba6c53833e0d42999b3afb384c8bf13454a7adf1"
      url "https://github.com/spacedock-dev/spacedock/releases/download/v#{version}/spacedock_#{version}_linux_arm64_edge.tar.gz"
    end
  end

  name "spacedock@next"
  desc "Workflow launcher and first-officer dispatch for agentic dev (edge channel)"
  homepage "https://github.com/spacedock-dev/spacedock"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on cask: [
      "agentsview",
    ]

  binary "spacedock@next"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/spacedock"]
  end

  # No zap stanza required

  caveats <<~EOS
    Recommended companion (install separately):
      safehouse  — sandboxes agent runs (https://agent-safehouse.dev)
      brew install eugene1g/safehouse/agent-safehouse
  EOS
end
