# This file was generated by GoReleaser. DO NOT EDIT.
cask "spacedock@next" do
  version "0.25.0"

  on_macos do
    on_intel do
      sha256 "27026e2bd5bad5efa8c8aae9a94ba4e100bcc99f0dd9936a395055ffdb7dc37d"
      url "https://github.com/spacedock-dev/spacedock/releases/download/v#{version}/spacedock_#{version}_darwin_amd64_edge.tar.gz"
    end
    on_arm do
      sha256 "af11577a176860c7708be8c2022810568ac08cc4fbaefcaece52e566c35bb371"
      url "https://github.com/spacedock-dev/spacedock/releases/download/v#{version}/spacedock_#{version}_darwin_arm64_edge.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "88a4fc986c0472a28677d944f01528e6d5b1e799d117e547cdf1cf0f163c7d26"
      url "https://github.com/spacedock-dev/spacedock/releases/download/v#{version}/spacedock_#{version}_linux_amd64_edge.tar.gz"
    end
    on_arm do
      sha256 "7b2647fa38de150838bc4ee8be0a99104969347656e921876f5b8cdeb315321b"
      url "https://github.com/spacedock-dev/spacedock/releases/download/v#{version}/spacedock_#{version}_linux_arm64_edge.tar.gz"
    end
  end

  name "spacedock@next"
  desc "Workflow launcher and first-officer dispatch for agentic dev (edge channel)"
  homepage "https://github.com/spacedock-dev/spacedock"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "spacedock",
    ]

  depends_on cask: [
      "agentsview",
    ]

  binary "spacedock"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/spacedock"]
  end

  # No zap stanza required

  caveats <<~EOS
    Recommended companion (install separately):
      safehouse  — sandboxes agent runs (https://agent-safehouse.dev)
      brew install eugene1g/safehouse/agent-safehouse
  EOS
end
